meta_product_name: "Lucy Burney Nutrition"
meta_title: "Lucy Burney Nutrition: Providing easy nutrition for all the family"
meta_description: "Check out my website!"
meta_image: "meta_img.png" # should exist in `app/assets/images/`
twitter_account: "@lucyburneynutrition"   # required for Twitter Cards
