meta_product_name: "Lucy Burney Nutrition"
meta_title: "Providing easy nutrition for all the family"
meta_description: "Check out my website!"
meta_image: "bluebells.png" # should exist in `app/assets/images/`
# twitter_account: "@lucyburneynutrition"   # required for Twitter Cards
